export enum ErrorType {
  WrongPassword = "WRONG_PASSWORD",
  EmptyKeyList = "EMPTY_KEY_LIST",
  RdnNotFound = "RDN_NOT_FOUND",
  XmlParseException = "XML_PARSE_EXCEPTION",
  SignatureValidation = "SIGNATURE_VALIDATION_ERROR",
}

export enum Method {
  None = "none",
  BrowseKeyStore = "browseKeyStore",
  ShowFileChooser = "showFileChooser",
  GetKeys = "getKeys",
  SetLocale = "setLocale",
  GetNotBefore = "getNotBefore",
  GetNotAfter = "getNotAfter",
  GetSubjectDN = "getSubjectDN",
  GetIssuerDN = "getIssuerDN",
  GetRdnByOid = "getRdnByOid",
  SignPlainData = "signPlainData",
  VerifyPlainData = "verifyPlainData",
  CreateCMSSignature = "createCMSSignature",
  VerifyCMSSignature = "verifyCMSSignature",
  CreateCMSSignatureFromFile = "createCMSSignatureFromFile",
  VerifyCMSSignatureFromFile = "verifyCMSSignatureFromFile",
  SignXml = "signXml",
  VerifyXml = "verifyXml",
  SignXmlByElementId = "signXmlByElementId",
  VerifyXmlByElementId = "verifyXmlByElementId",
  GetHash = "getHash",
}
